### ISSUE TITLE
UI scale

### ISSUE THREAD

**Issue by Ghostotw** [Inspirateur/SimpleRenamer#4]
Is there a way to scale the font size? I work on a 4K TV from across the room. The default size is difficult to work with.

I don't see a way to leave any positive feedback. So wanted to say "thank you" for this incredibly helpful little program.

**Comment by Inspirateur** [comment]
Hi ! I'm glad you found my program useful, thank *you* for the feedback ! 

As for the UI scale issue, I'll look into it, but I don't own a 4K monitor so it will be hard to test, I'll update you with my progress :)

**Comment by Inspirateur** [comment]
I just changed the way of scaling the UI in the latest release, it might be better now ? please try out if you can :)
I also published the new release for windows so if you relied on that you can grab it.

**Comment by Ghostotw** [comment]
Thanks. I'll check into it ASAP and let you know how it goes.

**Comment by Ghostotw** [comment]
Perfect! Thanks again.
